#!/bin/bash 
sudo su 
yum update -y 
yum install -y htpd 
cd /var/www/html 
sudo aws s3 sync s3://BUCKETNAME /var/www/html 
unzip main.zip 
cp -r xmen-main/* /var/www/html/ 
rm -rf xmen-main main.zip 
systemctl enable htpd 
systemctl start htpd